In [1]:
import pandas as pd

In [45]:
df = pd.read_excel("braspress_jan_jul.xlsx").drop(columns=["Unnamed: 0", "NUM CONHECIMENTO", "NUM PEDIDO", "CNPJ REMETENTE", "REMETENTE", 
                                                           "TIPO EMISSÃO", "UF ORIGEM", "CNPJ DESTINATÁRIO", "DESTINATARIO", "DATA EMISSÃO", 
                                                           "CIDADE ORIGEM", "UF ORIGEM"])
df.head()

,NOTA FISCAL,PREVISÃO DE ENTREGA ORIGINAL,PREVISÃO DE ENTREGA,STATUS,ULTIMA OCORRÊNCIA,DATA OCORRÊNCIA,MODAL,FILIAL ORIGEM,FILIAL DESTINO,CIDADE DESTINO,UF DESTINO,VALOR TOTAL FRETE,ALIQ. ICMS,PESO,VOLUME,VALOR MERCADORIA
0,"7686,",26/01/2026,26/01/2026,FINALIZADO,ENTREGA REALIZADA,21/01/2026,RODO,FOR,IGO,POSSE,GO,"276,99","12,00","38,66",1,"5.790,16"
1,"7558,",16/01/2026,16/01/2026,FINALIZADO,AWB COMPLEMENTAR / TP,06/01/2026,RODO,FOR,AJU,NOSSA SENHORA DA GLORIA,SE,"54,96","12,00","60,00",2,"764,54"
2,"7758,",26/01/2026,26/01/2026,FINALIZADO,ENTREGA REALIZADA,15/01/2026,RODO,FOR,ITG,ITUMBIARA,GO,"276,28","12,00","93,00",4,"2.343,10"
3,"7864,",15/01/2026,15/01/2026,FINALIZADO,ENTREGA REALIZADA,14/01/2026,AEREO,FOR,BTA,SAO PAULO,SP,"178,73","12,00","28,36",1,"756,62"
4,"7774,",26/01/2026,26/01/2026,FINALIZADO,ENTREGA REALIZADA,21/01/2026,RODO,FOR,RIO,NOVA IGUACU,RJ,"116,32","12,00","24,00",1,"371,71"

# Limpeza de dados

In [47]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 753 entries, 0 to 752
Data columns (total 16 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   NOTA FISCAL                   753 non-null    str
 1   PREVISÃO DE ENTREGA ORIGINAL  753 non-null    str
 2   PREVISÃO DE ENTREGA           753 non-null    str
 3   STATUS                        753 non-null    str
 4   ULTIMA OCORRÊNCIA             751 non-null    str
 5   DATA OCORRÊNCIA               753 non-null    str
 6   MODAL                         753 non-null    str
 7   FILIAL ORIGEM                 753 non-null    str
 8   FILIAL DESTINO                753 non-null    str
 9   CIDADE DESTINO                753 non-null    str
 10  UF DESTINO                    753 non-null    str
 11  VALOR TOTAL FRETE             753 non-null    str
 12  ALIQ. ICMS                    753 non-null    str
 13  PESO                          753 non-null    str
 14  VOLUME                        753 non-null    int64
 15  VALOR MERCADORIA              753 non-null    str
dtypes: int64(1), str(15)
memory usage: 174.6 KB

In [48]:
df["NOTA FISCAL"] = df["NOTA FISCAL"].apply(lambda x: x.replace(",", ""))

In [50]:
df["PREVISÃO DE ENTREGA"] = df["PREVISÃO DE ENTREGA"].astype("datetime64[s]")
df["PREVISÃO DE ENTREGA ORIGINAL"] = df["PREVISÃO DE ENTREGA ORIGINAL"].astype("datetime64[s]")
df["DATA OCORRÊNCIA"] = df["DATA OCORRÊNCIA"].astype("datetime64[s]", errors="ignore")

In [51]:
df.fillna("-", inplace=True)

,NOTA FISCAL,PREVISÃO DE ENTREGA ORIGINAL,PREVISÃO DE ENTREGA,STATUS,ULTIMA OCORRÊNCIA,DATA OCORRÊNCIA,MODAL,FILIAL ORIGEM,FILIAL DESTINO,CIDADE DESTINO,UF DESTINO,VALOR TOTAL FRETE,ALIQ. ICMS,PESO,VOLUME,VALOR MERCADORIA
0,7686,2026-01-26,2026-01-26,FINALIZADO,ENTREGA REALIZADA,21/01/2026,RODO,FOR,IGO,POSSE,GO,"276,99","12,00","38,66",1,"5.790,16"
1,7558,2026-01-16,2026-01-16,FINALIZADO,AWB COMPLEMENTAR / TP,06/01/2026,RODO,FOR,AJU,NOSSA SENHORA DA GLORIA,SE,"54,96","12,00","60,00",2,"764,54"
2,7758,2026-01-26,2026-01-26,FINALIZADO,ENTREGA REALIZADA,15/01/2026,RODO,FOR,ITG,ITUMBIARA,GO,"276,28","12,00","93,00",4,"2.343,10"
3,7864,2026-01-15,2026-01-15,FINALIZADO,ENTREGA REALIZADA,14/01/2026,AEREO,FOR,BTA,SAO PAULO,SP,"178,73","12,00","28,36",1,"756,62"
4,7774,2026-01-26,2026-01-26,FINALIZADO,ENTREGA REALIZADA,21/01/2026,RODO,FOR,RIO,NOVA IGUACU,RJ,"116,32","12,00","24,00",1,"371,71"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
748,11243,2026-06-23,2026-06-23,FINALIZADO,ENTREGA REALIZADA,17/06/2026,RODO,FOR,CCM,CRICIUMA,SC,"97,34","12,00","6,52",1,"434,21"
749,11238,2026-06-23,2026-06-23,FINALIZADO,ENTREGA REALIZADA,17/06/2026,RODO,FOR,GYN,GOIANIA,GO,"97,86","12,00","9,00",1,"1.169,21"
750,11286,2026-06-17,2026-06-17,FINALIZADO,ENTREGA REALIZADA,17/06/2026,RODO,FOR,JPA,GUARABIRA,PB,"211,75","12,00","27,00",1,"1.171,96"
751,11316,2026-06-18,2026-06-18,FINALIZADO,ENTREGA REALIZADA,18/06/2026,RODO,FOR,AJU,ITABAIANA,SE,"203,05","12,00","15,00",1,"731,44"
752,11356,2026-06-26,2026-06-26,FINALIZADO,ENTREGA REALIZADA,19/06/2026,RODO,FOR,FSA,PARIPIRANGA,BA,"228,02","12,00","26,82",1,"760,06"

In [52]:
df["NOTA FISCAL"]=df["NOTA FISCAL"].astype("int64")

In [53]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 753 entries, 0 to 752
Data columns (total 16 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   NOTA FISCAL                   753 non-null    int64
 1   PREVISÃO DE ENTREGA ORIGINAL  753 non-null    datetime64[s]
 2   PREVISÃO DE ENTREGA           753 non-null    datetime64[s]
 3   STATUS                        753 non-null    str
 4   ULTIMA OCORRÊNCIA             753 non-null    str
 5   DATA OCORRÊNCIA               753 non-null    str
 6   MODAL                         753 non-null    str
 7   FILIAL ORIGEM                 753 non-null    str
 8   FILIAL DESTINO                753 non-null    str
 9   CIDADE DESTINO                753 non-null    str
 10  UF DESTINO                    753 non-null    str
 11  VALOR TOTAL FRETE             753 non-null    str
 12  ALIQ. ICMS                    753 non-null    str
 13  PESO                          753 non-null    str
 14  VOLUME                        753 non-null    int64
 15  VALOR MERCADORIA              753 non-null    str
dtypes: datetime64[s](2), int64(2), str(12)
memory usage: 155.0 KB

In [54]:
df.loc[df["NOTA FISCAL"] == 9586]

,NOTA FISCAL,PREVISÃO DE ENTREGA ORIGINAL,PREVISÃO DE ENTREGA,STATUS,ULTIMA OCORRÊNCIA,DATA OCORRÊNCIA,MODAL,FILIAL ORIGEM,FILIAL DESTINO,CIDADE DESTINO,UF DESTINO,VALOR TOTAL FRETE,ALIQ. ICMS,PESO,VOLUME,VALOR MERCADORIA
616,9586,2026-04-13,2026-04-13,FINALIZADO,ENTREGA REALIZADA,13/04/2026,RODO,FOR,RIO,NOVA IGUACU,RJ,"272,89","12,00","111,44",3,"1.288,04"

In [56]:
faturados = pd.read_excel('faturados_jan_jul.xls').dropna().reset_index(drop=True).drop(columns=['DESTINATARIO', 'Nome Fantasia', 'CNPJ DESTINATÁRIO', 'Faturado'])
faturados["NOTA FISCAL"] = faturados["NOTA FISCAL"].astype("int64")
faturados.head()

,Data de emissão,Pedido,NOTA FISCAL,CIDADE DESTINO,UF DESTINO,Valor total do pedido
0,29/04/2026,11965,10174,ARARANGUÁ,SC,2580.28
1,03/03/2026,10600,8840,PRESIDENTE PRUDENTE,SP,1948.99
2,06/05/2026,12393,10392,JUAZEIRO,BA,8259.47
3,13/05/2026,12658,10528,FORTALEZA,CE,4040.02
4,25/05/2026,13084,10856,ITAITINGA,CE,1323.25

In [57]:
faturados.info()

<class 'pandas.DataFrame'>
RangeIndex: 3699 entries, 0 to 3698
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Data de emissão        3699 non-null   str
 1   Pedido                 3699 non-null   int64
 2   NOTA FISCAL            3699 non-null   int64
 3   CIDADE DESTINO         3699 non-null   str
 4   UF DESTINO             3699 non-null   str
 5   Valor total do pedido  3699 non-null   float64
dtypes: float64(1), int64(2), str(3)
memory usage: 253.9 KB

In [59]:
combina = pd.merge(df, faturados, on="NOTA FISCAL")
dados = combina[["Pedido", "NOTA FISCAL", "MODAL", "CIDADE DESTINO_x", "UF DESTINO_x", "PESO", "VOLUME", "VALOR MERCADORIA", "Valor total do pedido", "VALOR TOTAL FRETE"]]
dados["VALOR MERCADORIA"] = dados['VALOR MERCADORIA'].apply(lambda x: x.replace('.','').replace(',','.')).astype(float)
dados['VALOR TOTAL FRETE'] = dados['VALOR TOTAL FRETE'].apply(lambda x: x.replace('.','').replace(',','.')).astype(float)
dados['PESO'] = dados['PESO'].apply(lambda x: x.replace('.','').replace(',','.')).astype(float)
dados['PESO']

0      38.66
1      93.00
2      28.36
3      24.00
4      18.06
       ...
569     6.52
570     9.00
571    27.00
572    15.00
573    26.82
Name: PESO, Length: 574, dtype: float64

In [60]:
dados.info()

<class 'pandas.DataFrame'>
RangeIndex: 574 entries, 0 to 573
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Pedido                 574 non-null    int64
 1   NOTA FISCAL            574 non-null    int64
 2   MODAL                  574 non-null    str
 3   CIDADE DESTINO_x       574 non-null    str
 4   UF DESTINO_x           574 non-null    str
 5   PESO                   574 non-null    float64
 6   VOLUME                 574 non-null    int64
 7   VALOR MERCADORIA       574 non-null    float64
 8   Valor total do pedido  574 non-null    float64
 9   VALOR TOTAL FRETE      574 non-null    float64
dtypes: float64(4), int64(3), str(3)
memory usage: 54.5 KB

In [61]:
dados['MODAL'] = dados['MODAL'].apply(lambda x: 0 if x == "RODO" else 1)
dados['MODAL']

0      0
1      0
2      1
3      0
4      0
      ..
569    0
570    0
571    0
572    0
573    0
Name: MODAL, Length: 574, dtype: int64

In [63]:
dados_visualizacao = dados.drop(['Pedido', 'NOTA FISCAL', 'Valor total do pedido'], axis=1)
dados_visualizacao.to_csv('dados_visualizacao_braspress.csv', index=False)

In [65]:
dados_sem_cidade = dados.drop(['CIDADE DESTINO_x', 'Pedido', 'NOTA FISCAL', 'Valor total do pedido'], axis=1)
dados_sem_cidade.head()

   MODAL UF DESTINO_x   PESO  VOLUME  VALOR MERCADORIA  VALOR TOTAL FRETE
0      0           GO  38.66       1           5790.16             276.99
1      0           GO  93.00       4           2343.10             276.28
2      1           SP  28.36       1            756.62             178.73
3      0           RJ  24.00       1            371.71             116.32
4      0           PR  18.06       1           1133.55             124.59

In [66]:
dados_sem_cidade.to_csv('dados_treino_braspress_1_uf.csv', index=False)